CREATE TABLE IF NOT EXISTS label_posts
(
    post_id  INTEGER NOT NULL
    CONSTRAINT fk_post REFERENCES posts (id) ON DELETE CASCADE,
    label_id INTEGER NOT NULL CONSTRAINT fk_label REFERENCES labels (id) ON UPDATE CASCADE ON DELETE CASCADE
);
